# config.yaml

# 01_process_DR_Cluster

# 定义可替换的变量（想要进行流程的细胞类型）
celltype: "celltype_B"  # 可改为 celltype_B、celltype_T 等
#也可在命令行指定通配符：snakemake --config celltype=celltype_B all_process_DR_Cluster

# 输入输出路径
input:
  seurat: "output/s07_scanpy2seurat/{celltype}/subcell.rds"

output:
  result: "result_out/01_process_DR_Cluster/{celltype}/subcell.rds"
  figures: "figure_out/01_process_DR_Cluster/{celltype}/"

# 处理参数
params:
  species: "human"
  dims: 12 # 不要引号
  subsets:
    nFeature_RNA_min: 50  # 不要引号
    nFeature_RNA_max: 1000
    percent_mt_max: 8  # 不要引号

# 图表文件名配置
output_figures:
  vln_raw: "figure_out/01_process_DR_Cluster/{celltype}/vln_raw.png"
  scatter_raw: "figure_out/01_process_DR_Cluster/{celltype}/scatter_raw.png"
  vln_qc: "figure_out/01_process_DR_Cluster/{celltype}/vln_qc.png"
  scatter_qc: "figure_out/01_process_DR_Cluster/{celltype}/scatter_qc.png"
  elbow: "figure_out/01_process_DR_Cluster/{celltype}/elbow.png"

# 02_process_scRepertoire

# 定义可替换的变量（想要进行流程的分组信息）
group: "SLE_IR" #Skin_IR、Blood_IR、DLE_IR、SLE_IR

# 输入输出路径
input02: 
  contig: "data/{group}"

output02: 
  result: "result_out/02_process_scRepertoire/{group}"
  figures: "figure_out/02_process_scRepertoire/{group}"

# 处理参数
params02:
  parallel: "TRUE"

# 03_process_NMF_Enrichment
# 输入输出路径
input03:
  seurat: "output/s07_scanpy2seurat/{celltype}/subcell.rds"

output03:
  result: "result_out/03_process_NMF_Enrichment/{celltype}/nmf_seurat.rds"
  nmf_model: "result_out/03_process_NMF_Enrichment/{celltype}/nmf_initial.rds"
  final_model: "result_out/03_process_NMF_Enrichment/{celltype}/nmf_final.rds"
  rank_plot: "figure_out/03_process_NMF_Enrichment/{celltype}/rank_estimate.pdf"
  enrich_dir: "result_out/03_process_NMF_Enrichment/{celltype}/enrichment/"

# 处理参数
params03:
  species: "human"
  rank_start: 7
  rank_stop: 8
  rank_step: 1
  nrun: 15
  topN: 100
  resolution: 0.2
  # 可选：已有的NMF结果路径（用于跳过NMF计算）
  existing_nmf_model: null #"result_out/03_process_NMF_Enrichment/{celltype}/nmf_initial.rds"
  existing_final_nmf: null #"result_out/03_process_NMF_Enrichment/{celltype}/nmf_final.rds"

# 04_process_runGSVA.R
output04:
  gsva_result_dir: "result_out/04_process_runGSVA/{celltype}"
  gsva_plot_dir: "figure_out/04_process_runGSVA/{celltype}"

params04:
  species: "human"
  top_n: 10  # 每个cluster使用富集分析的前10个通路进行GSVA

# 05_plots_nmfAnno_enrichment.R
input05:
  seurat: "result_out/03_process_NMF_Enrichment/{celltype}/nmf_seurat.rds"
  pathway_df: "result_out/03_process_NMF_Enrichment/{celltype}/enrichment/top_pathways_per_cluster.csv"
  color_palette: "db/Rdatabase/05_plots_nmfAnno_enrichment/default_colors.csv"

output05:
  output_dir: "result_out/05_plots_nmfAnno_enrichment/{celltype}"
  output_plot_dir: "figure_out/05_plots_nmfAnno_enrichment/{celltype}"

params05: 
  species: "human"
  top_n: 10
  base_dir: "result_out/04_process_runGSVA/{celltype}"

# 06_process_Build_Geneset.R
# 基因集构建配置
input06:
  # 自定义基因集文件路径
  custom_tsv: "db/Rdatabase/06_process_Build_Geneset/custom_gene_sets.tsv"  

output06:
  gmt_files_dir: "result_out/06_process_Build_Geneset/{celltype}"

params06:
  # KEGG通路ID列表 (不带hsa前缀)
  kegg_ids: ["05323", "04662", "04620", "05322"]
  
  # GO ID列表
  go_ids: ["GO:0002200","GO:0016445","GO:0002208","GO:0015980","GO:0097009","GO:0006112","GO:0042113","GO:0002312","GO:0001783","GO:0035754","GO:0030183","GO:0001782","GO:0019724","GO:0042100","GO:0002322","GO:0050853","GO:0001788","GO:0019732","GO:0061760","GO:0019882","GO:0048006","GO:0019883","GO:0002483","GO:0002484","GO:0019884","GO:0002478"]


  # 物种
  species: "human"

# 07_process_scoreGSVA.R
input07:
  gmt_file: "result_out/06_process_Build_Geneset/{celltype}/all_gene_sets.gmt"
  seurat_rds: "result_out/03_process_NMF_Enrichment/{celltype}/nmf_seurat.rds"

output07:
  GSVA_files_dir: "result_out/07_process_scoreGSVA/{celltype}"
  GSVA_plots_dir: "figure_out/07_process_scoreGSVA/{celltype}"

# 08_plots_interestPathway.R
output08:
  prism_files_dir: "result_out/08_plots_interestPathway/{celltype}"
  prism_plots_dir: "figure_out/08_plots_interestPathway/{celltype}"

params08:
  target_group: "NMF_Cluster_5"
#  target_pathway: "leukocyte.mediated.immunity" #make.names后的名字