# config.yaml

# 01_process_DR_Cluster
# 输入输出路径
input:
  seurat: "output/s07_scanpy2seurat/celltype_ker/subcell.rds"

output:
  result: "result_out/01_process_DR_Cluster/celltype_ker/subcell.rds"
  figures: "figure_out/01_process_DR_Cluster/celltype_ker/"

# 处理参数
params:
  species: "human"
  dims: 20  # 不要引号
  subsets:
    nFeature_RNA_min: 50  # 不要引号
    nFeature_RNA_max: 7500
    percent_mt_max: 5  # 不要引号

# 图表文件名配置
output_figures:
  vln_raw: "figure_out/01_process_DR_Cluster/celltype_ker/vln_raw.png"
  scatter_raw: "figure_out/01_process_DR_Cluster/celltype_ker/scatter_raw.png"
  vln_qc: "figure_out/01_process_DR_Cluster/celltype_ker/vln_qc.png"
  scatter_qc: "figure_out/01_process_DR_Cluster/celltype_ker/scatter_qc.png"
  elbow: "figure_out/01_process_DR_Cluster/celltype_ker/elbow.pdf"

