name: Compass
channels:
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/main/
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/free/
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/conda-forge/
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=1.12
  - matplotlib>=3.4
  - pandas>=0.20
  - scikit-learn>=0.19
  - scipy>=1.0
  - statsmodels
  - click
  - pip
  - pip:
    - gurobipy>=11.0.0
